#pragma once

// Auto-generated by CMake. Do not edit manually.
#define PULSEPORT_VERSION "0.1.0"
#define PULSEPORT_VERSION_MAJOR 0
#define PULSEPORT_VERSION_MINOR 1
#define PULSEPORT_VERSION_PATCH 0
